name: Terraform CI

on:
  push:
    paths:
      - '**.tf'
      - '**.tfvars.example'
      - '.github/workflows/terraform-ci.yml'
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars.example'
      - '.github/workflows/terraform-ci.yml'

jobs:
  terraform-checks:
    name: Terraform Security & Format Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write
      contents: read
      actions: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: actions/cache@v3
        with:
          path: .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Initialize and Validate Terraform
        id: tf_init_validate
        run: |
          terraform init -backend=false
          terraform validate -json
          terraform fmt -check -recursive -diff
        continue-on-error: true

      - name: Run TFLint
        uses: reviewdog/action-tflint@v1.17.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          filter_mode: nofilter
          fail_on_error: true
          tflint_rulesets: terraform

      - name: Prepare Security Scans
        run: mkdir -p reports

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          format: sarif
          additional_args: |
            --minimum-severity HIGH
            --out reports/tfsec.sarif

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: reports/checkov.sarif
          soft_fail: true
          skip_check: CKV_AWS_*,CKV_AZURE_35,CKV_AZURE_44,CKV_AZURE_50,CKV2_AZURE_*,CKV_AZURE_59,CKV_AZURE_3
          download_external_modules: true
          quiet: true
          compact: true
          soft_fail_on: LOW,MEDIUM

      - name: Upload Security Reports
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports
          category: terraform-security

      - name: Post Results Summary
        if: always()
        run: |
          echo "### Terraform CI Results :rocket:" >> "$GITHUB_STEP_SUMMARY"
          echo "#### Terraform Checks" >> "$GITHUB_STEP_SUMMARY"
          echo "\`Status: ${{ steps.tf_init_validate.outcome }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "#### Security Scans" >> "$GITHUB_STEP_SUMMARY"
          echo "✅ Completed - Check Security tab for details" >> "$GITHUB_STEP_SUMMARY"

      - name: Set Job Status
        if: always()
        run: |
          if [[ "${{ steps.tf_init_validate.outcome }}" == "failure" ]]; then
            exit 1
          fi
